# Generated by Django 3.2.9 on 2024-04-25 03:02

from django.db import migrations, models
import django_enumfield.db.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hair_density',
            field=django_enumfield.db.fields.EnumField(default=1, enum=users.models.HairDensityEnum),
        ),
        migrations.AddField(
            model_name='user',
            name='hair_length',
            field=django_enumfield.db.fields.EnumField(default=1, enum=users.models.HairLengthEnum),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
