ONE_WAY_BUTTON = 'ONEWAY#'
MULTIPLE_WAY_BUTTON = 'MULTIPLEWAY#'
HAIR_LENGTH_BUTTON = 'STARTHAIRLENGTH#'
SHORT = 'SHORT#'
MEDIUM = 'MEDIUM#'
LONG = 'LONG#'
HAIR_DENSITY_BUTTON = 'STARTHAIRDENSITY#'
THIN = 'THIN#'
THICK = 'THICK#'
CONFIRM_SELECT_HAIR_BUTTON = 'CONFIRMSELECTHAIR#'
HAIR_LENGTH = 'HAIRLENGTH#'


