# Generated by Django 3.2.9 on 2024-04-25 03:02

from django.db import migrations, models
import schedules.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureNonPermanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_1_duration_min', models.FloatField(verbose_name='Минимальное время первого этапа')),
                ('stage_2_wait_min', models.FloatField(verbose_name='Минимальное время второго этапа')),
                ('stage_3_duration_min', models.FloatField(verbose_name='Минимальное время третьего этапа')),
            ],
            bases=(schedules.models.Procedure, models.Model),
        ),
        migrations.CreateModel(
            name='ProcedurePermanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.FloatField(verbose_name='Минимальное время процедуры')),
            ],
            bases=(schedules.models.Procedure, models.Model),
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Выходной день')),
                ('work_hour_start', models.TimeField(default='09:00:00', verbose_name='Начало рабочего дня')),
                ('work_hour_end', models.TimeField(default='18:00:00', verbose_name='Конец рабочего дня')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'ordering': ['date'],
            },
        ),
    ]
