# Generated by Django 3.2.9 on 2024-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240425_1102'),
        ('schedules', '0002_auto_20240427_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='workday',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='workday_appointment', to='schedules.Appointment'),
        ),
    ]
