# Generated by Django 3.2.9 on 2024-04-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240425_1102'),
        ('schedules', '0003_auto_20240428_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя процедуры'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
