# Generated by Django 3.2.9 on 2024-05-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240425_1102'),
        ('schedules', '0005_auto_20240429_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['-date'], 'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='available_slot',
            field=models.BooleanField(default=False, verbose_name='Доступный ВС'),
        ),
        migrations.CreateModel(
            name='UserAuthenticationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_photo_first', models.ImageField(blank=True, upload_to='authentication_photos/')),
                ('hair_photo_second', models.ImageField(blank=True, upload_to='authentication_photos/')),
                ('hair_photo_three', models.ImageField(blank=True, upload_to='authentication_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_requests', to='users.user')),
            ],
            options={
                'verbose_name': 'Запрос аутентификации',
                'verbose_name_plural': 'Запросы аутентификации',
                'ordering': ['-created_at'],
            },
        ),
    ]
