# Generated by Django 3.2.9 on 2024-05-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20240502_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationrequest',
            name='hair_photo_first',
            field=models.ImageField(blank=True, upload_to='authentication_photos/', verbose_name='Первая фотография волос'),
        ),
        migrations.AlterField(
            model_name='userauthenticationrequest',
            name='hair_photo_second',
            field=models.ImageField(blank=True, upload_to='authentication_photos/', verbose_name='Вторая фотография волос'),
        ),
        migrations.AlterField(
            model_name='userauthenticationrequest',
            name='hair_photo_three',
            field=models.ImageField(blank=True, upload_to='authentication_photos/', verbose_name='Третья фотография волос'),
        ),
    ]
